<?php

if (!defined('IN_PHPBB'))
{
    exit;
}

if (empty($lang) || !is_array($lang))
{
    $lang = array();
}


$lang = array_merge($lang, array(
    'ADD_ATTACHMENT'			=> 'আপলোড সংযুক্তি',
    'ADD_ATTACHMENT_EXPLAIN'	=> 'যদি আপনি এক বা একাধিক ফাইল সংযুক্ত করতে চান তবে নীচের বিবরণগুলি লিখুন।',
    'ADD_FILE'					=> 'ফাইল যোগ করুন',
    'ADD_POLL'					=> 'পোল তৈরি',
    'ADD_POLL_EXPLAIN'			=> 'আপনি যদি আপনার বিষয়বস্তুর একটি পোষ্ট যোগ করতে না চান তবে ক্ষেত্রগুলি খালি রাখুন।',
    'ALREADY_DELETED'			=> 'দুঃখিত কিন্তু এই বার্তা ইতিমধ্যেই মুছে ফেলা হয়েছে।',
    'ATTACH_DISK_FULL'			=> 'এই সংযুক্তি পোস্ট করার জন্য যথেষ্ট বিনামূল্যে ডিস্ক জায়গা নেই',
    'ATTACH_QUOTA_REACHED'			=> 'দুঃখিত, বোর্ড সংযুক্তি কোটা পৌঁছেছে।',
    'ATTACH_SIG'				=> 'Attach a signature (signatures can be altered via the UCP)',

    'BBCODE_A_HELP'				=> 'ইনলাইন আপলোড করা সংযুক্তি: [attachment=]filename.ext[/attachment]',
    'BBCODE_B_HELP'				=> 'বোল্ড: [b]text[/b]',
    'BBCODE_C_HELP'				=> 'কোড: [code]code[/code]',
    'BBCODE_D_HELP'				=> 'ফ্ল্যাশ: [flash=width,height]http://url[/flash]',
    'BBCODE_F_HELP'				=> 'অক্ষরের আকার: [size=85]small text[/size]',
    'BBCODE_IS_OFF'				=> '%sBBCode%s is <em>OFF</em>',
    'BBCODE_IS_ON'				=> '%sBBCode%s is <em>ON</em>',
    'BBCODE_I_HELP'				=> 'বাঁকা: [i]text[/i]',
    'BBCODE_L_HELP'				=> 'তালিকা: [list][*]text[/list]',
    'BBCODE_LISTITEM_HELP'		=> 'তালিকা আইটেম: [*]text',
    'BBCODE_O_HELP'				=> 'Ordered list: e.g. [list=1][*]First point[/list] or [list=a][*]Point a[/list]',
    'BBCODE_P_HELP'				=> 'চিত্র ঢোকান: [img]http://image_url[/img]',
    'BBCODE_Q_HELP'				=> 'Quote text: [quote]text[/quote]',
    'BBCODE_S_HELP'				=> 'ফন্ট রঙ: [color=red]text[/color] or [color=#FF0000]text[/color]',
    'BBCODE_U_HELP'				=> 'পাঠ্য নিম্নরেখা: [u]text[/u]',
    'BBCODE_W_HELP'				=> 'Insert URL: [url]http://url[/url] or [url=http://url]URL text[/url]',
    'BBCODE_Y_HELP'				=> 'তালিকা: Add list element',
    'BUMP_ERROR'				=> 'শেষ পোস্টের পরই আপনি এই বিষয়টিকে দমন করতে পারবেন না।',

    'CANNOT_DELETE_REPLIED'		=> 'দুঃখিত কিন্তু আপনি কেবল এমন পোস্ট মুছে ফেলতে পারেন যা উত্তর দেওয়া হয়নি।',
    'CANNOT_EDIT_POST_LOCKED'	=> 'এই পোস্টটি লক করা হয়েছে। আপনি আর পোস্টটি সম্পাদনা করতে পারবেন না',
    'CANNOT_EDIT_TIME'			=> 'আপনি যে পোস্টটি আর সম্পাদনা বা মুছে ফেলতে পারবেন না।',
    'CANNOT_POST_ANNOUNCE'		=> 'দুঃখিত কিন্তু আপনি ঘোষণা পোস্ট করতে পারেন না।',
    'CANNOT_POST_STICKY'		=> 'দুঃখিত কিন্তু আপনি স্টিকি বিষয় পোস্ট করতে পারবেন না।',
    'CHANGE_TOPIC_TO'			=> 'বিষয়ের ধরন পরিবর্তন করুন',
    'CHARS_POST_CONTAINS'		=> array(
        1	=> 'Your message contains %1$d character.',
        2	=> 'Your message contains %1$d characters.',
    ),
    'CHARS_SIG_CONTAINS'		=> array(
        1	=> 'Your signature contains %1$d character.',
        2	=> 'Your signature contains %1$d characters.',
    ),
    'CLOSE_TAGS'				=> 'ট্যাগ বন্ধ করুন',
    'CURRENT_TOPIC'				=> 'বর্তমান টপিক',

    'DELETE_FILE'				=> 'ফাইল মুছুন',
    'DELETE_MESSAGE'			=> 'বার্তা মুছুন',
    'DELETE_MESSAGE_CONFIRM'	=> 'আপনি কি এই বার্তাটি মুছে দেওয়ার বিষয়ে নিশ্চিত?',
    'DELETE_OWN_POSTS'			=> 'দুঃখিত কিন্তু আপনি শুধুমাত্র আপনার নিজের পোস্ট মুছে দিতে পারেন।',
    'DELETE_PERMANENTLY'		=> 'স্থায়ীভাবে মুছুন',
    'DELETE_POST_CONFIRM'		=> 'আপনি কি নিশ্চিত যে আপনি এই পোস্টটি মুছতে চান?',
    'DELETE_POST_PERMANENTLY_CONFIRM'	=> 'Are you sure you want to <strong>permanently</strong> delete this post?',
    'DELETE_POST_PERMANENTLY'	=> array(
        1	=> 'Permanently delete this post so it can not be recovered',
        2	=> 'Permanently delete %1$d posts so they can not be recovered',
    ),
    'DELETE_POSTS_CONFIRM'		=> 'আপনি কি এই পোস্টগুলি মুছে দিতে চান?',
    'DELETE_POSTS_PERMANENTLY_CONFIRM'	=> 'Are you sure you want to <strong>permanently</strong> delete these posts?',
    'DELETE_REASON'				=> 'মুছে ফেলার কারণ',
    'DELETE_REASON_EXPLAIN'		=> 'মুছে ফেলার জন্য নির্দিষ্ট কারণটি মডারেটরদের কাছে দৃশ্যমান হবে।',
    'DELETE_POST_WARN'			=> 'এই পোস্টটি মুছুন',
    'DELETE_TOPIC_CONFIRM'		=> 'আপনি কি এই টপিক মুছে ফেলতে চান?',
    'DELETE_TOPIC_PERMANENTLY'	=> array(
        1	=> 'এই বিষয়টিকে স্থায়ীভাবে মুছে ফেলুন যাতে এটি পুনরুদ্ধার করা যায় না',
        2	=> 'Permanently delete %1$d topics so they can not be recovered',
    ),
    'DELETE_TOPIC_PERMANENTLY_CONFIRM'	=> 'Are you sure you want to <strong>permanently</strong> delete this topic?',
    'DELETE_TOPICS_CONFIRM'		=> 'আপনি কি এই টপিকগুলি মুছে ফেলতে চান?',
    'DELETE_TOPICS_PERMANENTLY_CONFIRM'	=> 'Are you sure you want to <strong>permanently</strong> delete these topics?',
    'DISABLE_BBCODE'			=> 'BBCode অক্ষম করুন',
    'DISABLE_MAGIC_URL'			=> 'URL গুলি স্বয়ংক্রিয়ভাবে বিশ্লেষণ করবেন না',
    'DISABLE_SMILIES'			=> 'স্মাইলি অক্ষম করুন',
    'DISALLOWED_CONTENT'		=> 'The upload was rejected because the uploaded file was identified as a possible attack vector.',
    'DISALLOWED_EXTENSION'		=> 'The extension %s is not allowed.',
    'DRAFT_LOADED'				=> 'Draft loaded into posting area, you may want to finish your post now.<br />Your draft will be deleted after submitting this post.',
    'DRAFT_LOADED_PM'			=> 'Draft loaded into message area, you may want to finish your private message now.<br />Your draft will be deleted after submitting this private message.',
    'DRAFT_SAVED'				=> 'খসড়া সফলভাবে সংরক্ষিত।',
    'DRAFT_TITLE'				=> 'খসড়া শিরোনাম',

    'EDIT_REASON'				=> 'এই পোস্টটি সম্পাদনা করার কারণ',
    'EMPTY_FILEUPLOAD'			=> 'আপলোড করা ফাইল খালি আছে।',
    'EMPTY_MESSAGE'				=> 'পোস্ট করার সময় আপনাকে অবশ্যই একটি বার্তা লিখতে হবে।',
    'EMPTY_REMOTE_DATA'			=> 'ফাইল আপলোড করা যায়নি, ফাইলটি ম্যানুয়ালি আপলোড করার চেষ্টা করুন।',

    'FLASH_IS_OFF'				=> '[flash] is <em>OFF</em>',
    'FLASH_IS_ON'				=> '[flash] is <em>ON</em>',
    'FLOOD_ERROR'				=> 'You cannot make another post so soon after your last.',
    'FONT_COLOR'				=> 'ফন্ট রঙ',
    'FONT_COLOR_HIDE'			=> 'ফন্ট রঙ দেখান',
    'FONT_HUGE'					=> 'বিশাল',
    'FONT_LARGE'				=> 'বড়',
    'FONT_NORMAL'				=> 'সাধারণ',
    'FONT_SIZE'					=> 'অক্ষরের আকার',
    'FONT_SMALL'				=> 'ছোট',
    'FONT_TINY'					=> 'অতি ক্ষুদ্র',

    'GENERAL_UPLOAD_ERROR'		=> 'Could not upload attachment to %s.',

    'IMAGES_ARE_OFF'			=> '[img] is <em>OFF</em>',
    'IMAGES_ARE_ON'				=> '[img] is <em>ON</em>',
    'INVALID_FILENAME'			=> '%s is an invalid filename.',

    'LOAD'						=> 'লোড',
    'LOAD_DRAFT'				=> 'লোড ড্রাফ্ট',
    'LOAD_DRAFT_EXPLAIN'		=> 'Here you are able to select the draft you want to continue writing. Your current post will be cancelled, all current post contents will be deleted. View, edit and delete drafts within your User Control Panel.',
    'LOGIN_EXPLAIN_BUMP'		=> 'এই ফোরামে বিষয়গুলিকে বাঁধা দেওয়ার জন্য আপনাকে লগইন করতে হবে।',
    'LOGIN_EXPLAIN_DELETE'		=> 'এই ফোরামে পোস্ট মুছে ফেলার জন্য আপনাকে লগইন করতে হবে।',
    'LOGIN_EXPLAIN_POST'		=> 'এই ফোরামে পোস্ট করার জন্য আপনাকে লগইন করতে হবে।',
    'LOGIN_EXPLAIN_QUOTE'		=> 'এই ফোরামে পোস্ট উদ্ধৃত করার জন্য আপনাকে লগইন করতে হবে।',
    'LOGIN_EXPLAIN_REPLY'		=> 'এই ফোরামে থাকা বিষয়গুলির উত্তর দেওয়ার জন্য আপনাকে লগ ইন করতে হবে।',

    'MAX_FONT_SIZE_EXCEEDED'	=> 'You may only use fonts up to size %d.',
    'MAX_FLASH_HEIGHT_EXCEEDED'	=> array(
        1	=> 'Your flash files may only be up to %d pixel high.',
        2	=> 'Your flash files may only be up to %d pixels high.',
    ),
    'MAX_FLASH_WIDTH_EXCEEDED'	=> array(
        1	=> 'Your flash files may only be up to %d pixel wide.',
        2	=> 'Your flash files may only be up to %d pixels wide.',
    ),
    'MAX_IMG_HEIGHT_EXCEEDED'	=> array(
        1	=> 'Your images may only be up to %1$d pixel high.',
        2	=> 'Your images may only be up to %1$d pixels high.',
    ),
    'MAX_IMG_WIDTH_EXCEEDED'	=> array(
        1	=> 'Your images may only be up to %d pixel wide.',
        2	=> 'Your images may only be up to %d pixels wide.',
    ),

    'MESSAGE_BODY_EXPLAIN'		=> array(
        0	=> '', // zero means no limit, so we don't view a message here.
        1	=> 'Enter your message here, it may contain no more than <strong>%d</strong> character.',
        2	=> 'Enter your message here, it may contain no more than <strong>%d</strong> characters.',
    ),
    'MESSAGE_DELETED'			=> 'এই বার্তাটি সফলভাবে মোছা হয়েছে।',
    'MORE_SMILIES'				=> 'আরো স্মাইলি দেখুন',
    'NOTIFY_REPLY'				=> 'একটি উত্তর পোস্ট করা হয় যখন আমাকে অবহিত',
    'NOT_UPLOADED'				=> 'ফাইল আপলোড করা যায়নি।',
    'NO_DELETE_POLL_OPTIONS'	=> 'আপনি বিদ্যমান পোল অপশন মুছে ফেলতে পারবেন না।',
    'NO_PM_ICON'				=> 'কোন PM আইকন',
    'NO_POLL_TITLE'				=> 'আপনি একটি পোল শিরোনাম লিখতে হবে।',
    'NO_POST'					=> 'অনুরোধকৃত পোস্টটি বিদ্যমান নেই।',
    'NO_POST_MODE'				=> 'কোন পোস্ট মোড নির্দিষ্ট করা হয় না।',
    'NO_TEMP_DIR'				=> 'অস্থায়ী ফোল্ডারের পাওয়া যায়নি বা লিখনযোগ্য নয়।',

    'PARTIAL_UPLOAD'			=> 'আপলোড করা ফাইলটি আংশিক আপলোড করা হয়েছিল। ',
    'PHP_UPLOAD_STOPPED'		=> 'পিএইচপি এক্সটেনশন ফাইল আপলোড বন্ধ করেছে।',
    'PHP_SIZE_NA'				=> 'The attachment’s file size is too large.<br />Could not determine the maximum size defined by PHP in php.ini.',
    'PHP_SIZE_OVERRUN'			=> 'The attachment’s file size is too large, the maximum upload size is %1$d %2$s.<br />Please note this is set in php.ini and cannot be overridden.',
    'PLACE_INLINE'				=> 'ইনলাইন বসান',
    'POLL_DELETE'				=> 'ভোট বাতিল করুন',
    'POLL_FOR'					=> 'চালান পোল',
    'POLL_FOR_EXPLAIN'			=> 'কখনও কখনও শেষ ভোটের জন্য 0 লিখুন।',
    'POLL_MAX_OPTIONS'			=> 'প্রতি ব্যবহারকারীর বিকল্প',
    'POLL_MAX_OPTIONS_EXPLAIN'	=> 'এই ভোট দেওয়ার সময় প্রতিটি ব্যবহারকারীই নির্বাচন করতে পারে এমন সংখ্যাগুলি',
    'POLL_OPTIONS'				=> 'পোল অপশন',
    'POLL_OPTIONS_EXPLAIN'		=> array(
        1	=> 'Place each option on a new line. You may enter <strong>%d</strong> option.',
        2	=> 'Place each option on a new line. You may enter up to <strong>%d</strong> options.',
    ),
    'POLL_OPTIONS_EDIT_EXPLAIN'		=> array(
        1	=> 'Place each option on a new line. You may enter <strong>%d</strong> option. If you remove or add options all previous votes will be reset.',
        2	=> 'Place each option on a new line. You may enter up to <strong>%d</strong> options. If you remove or add options all previous votes will be reset.',
    ),
    'POLL_QUESTION'				=> 'ভোটের প্রশ্ন',
    'POLL_TITLE_TOO_LONG'		=> 'জরিপের শিরোনামে 100 অক্ষরের কম সংখ্যক থাকা আবশ্যক।',
    'POLL_TITLE_COMP_TOO_LONG'	=> 'আপনার পোল শিরোনামের প্যাডেড আকার খুব বড়, বিবিসিডস বা স্মাইলি মুছে ফেলার কথা বিবেচনা করুন।',
    'POLL_VOTE_CHANGE'			=> 'পুনরায় ভোট দেওয়ার অনুমতি দিন',
    'POLL_VOTE_CHANGE_EXPLAIN'	=> 'যদি সক্রিয় ব্যবহারকারীরা তাদের ভোট পরিবর্তন করতে সক্ষম হয়।',
    'POSTED_ATTACHMENTS'		=> 'পোস্ট সংযুক্তি',
    'POST_APPROVAL_NOTIFY'		=> 'আপনার পোস্ট অনুমোদিত হলে আপনাকে অবহিত করা হবে।',
    'POST_CONFIRMATION'			=> 'পোস্টের নিশ্চিতকরণ',
    'POST_CONFIRM_EXPLAIN'		=> 'To prevent automated posts the board requires you to enter a confirmation code. The code is displayed in the image you should see below. If you are visually impaired or cannot otherwise read this code please contact the %sBoard Administrator%s.',
    'POST_DELETED'				=> 'এই পোস্টটি সফলভাবে মোছা হয়েছে।',
    'POST_EDITED'				=> 'এই পোস্টটি সফলভাবে সম্পাদনা করা হয়েছে।',
    'POST_EDITED_MOD'			=> 'এই পোস্টটি সফলভাবে সম্পাদনা করা হয়েছে, তবে এটি সার্বজনীনভাবে দর্শনীয় হওয়ার আগে একটি মডারেটর দ্বারা অনুমোদিত হতে হবে।',
    'POST_GLOBAL'				=> 'গ্লোবাল',
    'POST_ICON'					=> 'পোস্ট আইকন',
    'POST_NORMAL'				=> 'সাধারণ',
    'POST_REVIEW'				=> 'পোস্ট পর্যালোচনা',
    'POST_REVIEW_EDIT'			=> 'পোস্ট পর্যালোচনা',
    'POST_REVIEW_EDIT_EXPLAIN'	=> 'This post has been altered by another user while you were editing it. You may wish to review the current version of this post and adjust your edits.',
    'POST_REVIEW_EXPLAIN'		=> 'At least one new post has been made to this topic. You may wish to review your post in light of this.',
    'POST_STORED'				=> 'এই বার্তাটি সফলভাবে পোস্ট করা হয়েছে।',
    'POST_STORED_MOD'			=> 'এই বার্তাটি সফলভাবে জমা দেওয়া হয়েছে, তবে এটি সার্বজনীনভাবে দর্শনীয় হওয়ার আগে একজন মডারেটর দ্বারা অনুমোদিত হতে হবে।',
    'POST_TOPIC_AS'				=> 'Post topic as',
    'PROGRESS_BAR'				=> 'Progress bar',

    'QUOTE_DEPTH_EXCEEDED'		=> array(
        1	=> 'You may embed only %d quote within each other.',
        2	=> 'You may embed only %d quotes within each other.',
    ),
    'QUOTE_NO_NESTING'			=> 'You may not embed quotes within each other.',

    'REMOTE_UPLOAD_TIMEOUT'		=> 'নির্দিষ্ট ফাইলটি আপলোড করা যায়নি কারণ অনুরোধের সময় শেষ হয়েছে',
    'SAVE'						=> 'সংরক্ষণ',
    'SAVE_DATE'					=> 'এ সংরক্ষণ করুন',
    'SAVE_DRAFT'				=> 'খসড়া সংরক্ষণ',
    'SAVE_DRAFT_CONFIRM'		=> 'Please note that saved drafts only include the subject and the message, any other element will be removed. Do you want to save your draft now?',
    'SMILIES'					=> 'Smilies',
    'SMILIES_ARE_OFF'			=> 'Smilies are <em>OFF</em>',
    'SMILIES_ARE_ON'			=> 'Smilies are <em>ON</em>',
    'STICKY_ANNOUNCE_TIME_LIMIT'=> 'Sticky/Announcement/Global time limit',
    'STICK_TOPIC_FOR'			=> 'Stick topic for',
    'STICK_TOPIC_FOR_EXPLAIN'	=> 'Enter 0 for a never ending Sticky/Announcement/Global. Please note that this number is relative to the date of the post.',
    'STYLES_TIP'				=> 'টিপস: শৈলী নির্বাচিত পাঠ দ্রুত প্রয়োগ করা যায়।',

    'TOO_FEW_CHARS'				=> 'আপনার বার্তাটিতে খুব কম অক্ষর রয়েছে।',
    'TOO_FEW_CHARS_LIMIT'		=> array(
        1	=> 'You need to enter at least %1$d character.',
        2	=> 'You need to enter at least %1$d characters.',
    ),
    'TOO_FEW_POLL_OPTIONS'		=> 'You must enter at least two poll options.',
    'TOO_MANY_ATTACHMENTS'		=> 'Cannot add another attachment, %d is the maximum.',
    'TOO_MANY_CHARS'			=> 'আপনার বার্তাটিতে অনেক অক্ষর রয়েছে। ',
    'TOO_MANY_CHARS_LIMIT'		=> array(
        2	=> 'The maximum number of allowed characters is %1$d.',
    ),
    'TOO_MANY_POLL_OPTIONS'		=> 'You have tried to enter too many poll options.',
    'TOO_MANY_SMILIES'			=> 'Your message contains too many smilies. The maximum number of smilies allowed is %d.',
    'TOO_MANY_URLS'				=> 'Your message contains too many URLs. The maximum number of URLs allowed is %d.',
    'TOO_MANY_USER_OPTIONS'		=> 'You cannot specify more options per user than existing poll options.',
    'TOPIC_BUMPED'				=> 'Topic has been bumped successfully.',

    'UNAUTHORISED_BBCODE'		=> 'You cannot use certain BBCodes: %s.',
    'UNGLOBALISE_EXPLAIN'		=> 'To switch this topic back from being global to a normal topic, you need to select the forum you wish this topic to be displayed.',
    'UNSUPPORTED_CHARACTERS_MESSAGE'	=> 'Your message contains the following unsupported characters:<br />%s',
    'UNSUPPORTED_CHARACTERS_SUBJECT'	=> 'Your subject contains the following unsupported characters:<br />%s',
    'UPDATE_COMMENT'			=> 'মন্তব্য হালনাগাদ',
    'URL_INVALID'				=> 'আপনার নির্দিষ্ট URL টি অবৈধ।',
    'URL_NOT_FOUND'				=> 'নির্দিষ্ট ফাইলটি পাওয়া যায়নি।',
    'URL_IS_OFF'				=> '[url] is <em>OFF</em>',
    'URL_IS_ON'					=> '[url] is <em>ON</em>',
    'USER_CANNOT_BUMP'			=> 'You cannot bump topics in this forum.',
    'USER_CANNOT_DELETE'		=> 'আপনি এই ফোরামে পোস্টগুলি মুছে ফেলতে পারবেন না।',
    'USER_CANNOT_EDIT'			=> 'আপনি এই ফোরামে পোস্ট সম্পাদনা করতে পারবেন না।',
    'USER_CANNOT_REPLY'			=> 'আপনি এই ফোরামে উত্তর দিতে পারেন না।',
    'USER_CANNOT_FORUM_POST'	=> 'ফোরামের ফোরামের কারণে আপনি এই ফোরামে পোস্টিং অপারেশন করতে পারবেন না। এটি সমর্থন করে না। ',

    'VIEW_MESSAGE'				=> '%sView your submitted message%s',
    'VIEW_PRIVATE_MESSAGE'		=> '%sView your submitted private message%s',

    'WRONG_FILESIZE'			=> 'The file is too big, maximum allowed size is %1$d %2$s.',
    'WRONG_SIZE'				=> 'The image must be at least %1$s wide, %2$s high and at most %3$s wide and %4$s high. The submitted image is %5$s wide and %6$s high.',
));
