<?php
/**
*
* This file is part of the phpBB Forum Software package.
*
* @copyright (c) phpBB Limited <https://www.phpbb.com>
* @license GNU General Public License, version 2 (GPL-2.0)
*
* For full copyright and license information, please see
* the docs/CREDITS.txt file.
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

// Privacy policy and T&C
$lang = array_merge($lang, array(
	'TERMS_OF_USE_CONTENT'	=> 'By accessing “%1$s” (hereinafter “we”, “us”, “our”, “%1$s”, “%2$s”), you agree to be legally bound by the following terms. If you do not agree to be legally bound by all of the following terms then please do not access and/or use “%1$s”. We may change these at any time and we’ll do our utmost in informing you, though it would be prudent to review this regularly yourself as your continued usage of “%1$s” after changes mean you agree to be legally bound by these terms as they are updated and/or amended.<br />
	<br />
	Our forums are powered by phpBB (hereinafter “they”, “them”, “their”, “phpBB software”, “www.phpbb.com”, “phpBB Limited”, “phpBB Teams”) which is a bulletin board solution released under the “<a href="http://opensource.org/licenses/gpl-2.0.php">GNU General Public License v2</a>” (hereinafter “GPL”) and can be downloaded from <a href="https://www.phpbb.com/">www.phpbb.com</a>. The phpBB software only facilitates internet based discussions; phpBB Limited is not responsible for what we allow and/or disallow as permissible content and/or conduct. For further information about phpBB, please see: <a href="https://www.phpbb.com/">https://www.phpbb.com/</a>.<br />
	<br />
	You agree not to post any abusive, obscene, vulgar, slanderous, hateful, threatening, sexually-orientated or any other material that may violate any laws be it of your country, the country where “%1$s” is hosted or International Law. Doing so may lead to you being immediately and permanently banned, with notification of your Internet Service Provider if deemed required by us. The IP address of all posts are recorded to aid in enforcing these conditions. You agree that “%1$s” have the right to remove, edit, move or close any topic at any time should we see fit. As a user you agree to any information you have entered to being stored in a database. While this information will not be disclosed to any third party without your consent, neither “%1$s” nor phpBB shall be held responsible for any hacking attempt that may lead to the data being compromised.
	',

	'PRIVACY_POLICY'		=> 'This policy explains in detail how “%1$s” along with its affiliated companies (hereinafter “we”, “us”, “our”, “%1$s”, “%2$s”) and phpBB (hereinafter “they”, “them”, “their”, “phpBB software”, “www.phpbb.com”, “phpBB Limited”, “phpBB Teams”) use any information collected during any session of usage by you (hereinafter “your information”).<br />
	<br />
	Your information is collected via two ways. Firstly, by browsing “%1$s” will cause the phpBB software to create a number of cookies, which are small text files that are downloaded on to your computer’s web browser temporary files. The first two cookies just contain a user identifier (hereinafter “user-id”) and an anonymous session identifier (hereinafter “session-id”), automatically assigned to you by the phpBB software. A third cookie will be created once you have browsed topics within “%1$s” and is used to store which topics have been read, thereby improving your user experience.<br />
	<br />
	We may also create cookies external to the phpBB software whilst browsing “%1$s”, though these are outside the scope of this document which is intended to only cover the pages created by the phpBB software. The second way in which we collect your information is by what you submit to us. This can be, and is not limited to: posting as an anonymous user (hereinafter “anonymous posts”), registering on “%1$s” (hereinafter “your account”) and posts submitted by you after registration and whilst logged in (hereinafter “your posts”).<br />
	<br />
	Your account will at a bare minimum contain a uniquely identifiable name (hereinafter “your user name”), a personal password used for logging into your account (hereinafter “your password”) and a personal, valid email address (hereinafter “your email”). Your information for your account at “%1$s” is protected by data-protection laws applicable in the country that hosts us. Any information beyond your user name, your password, and your email address required by “%1$s” during the registration process is either mandatory or optional, at the discretion of “%1$s”. In all cases, you have the option of what information in your account is publicly displayed. Furthermore, within your account, you have the option to opt-in or opt-out of automatically generated emails from the phpBB software.<br />
	<br />
	Your password is ciphered (a one-way hash) so that it is secure. However, it is recommended that you do not reuse the same password across a number of different websites. Your password is the means of accessing your account at “%1$s”, so please guard it carefully and under no circumstance will anyone affiliated with “%1$s”, phpBB or another 3rd party, legitimately ask you for your password. Should you forget your password for your account, you can use the “I forgot my password” feature provided by the phpBB software. This process will ask you to submit your user name and your email, then the phpBB software will generate a new password to reclaim your account.<br />
	',
));

// Common language entries
$lang = array_merge($lang, array(
	'ACCOUNT_ACTIVE'				=> 'আপনার অ্যাকাউন্ট এখন সক্রিয় করা হয়েছে। নিবন্ধন করার জন্য আপনাকে ধন্যবাদ.',
	'ACCOUNT_ACTIVE_ADMIN'			=> 'অ্যাকাউন্ট এখন সক্রিয় করা হয়েছে।',
	'ACCOUNT_ACTIVE_PROFILE'		=> 'আপনার অ্যাকাউন্টটি সফলভাবে পুনরায় সক্রিয় করা হয়েছে।',
	'ACCOUNT_ADDED'					=> 'নিবন্ধীকরণের জন্য আপনাকে ধন্যবাদ, আপনার অ্যাকাউন্ট তৈরি করা হয়েছে। আপনি এখন আপনার ব্যবহারকারী নাম এবং পাসওয়ার্ড দিয়ে লগইন করতে পারেন। ',
	'ACCOUNT_COPPA'					=> 'আপনার অ্যাকাউন্ট তৈরি করা হয়েছে কিন্তু অনুমোদন করা হয়েছে, বিস্তারিত জানার জন্য আপনার ইমেইল চেক করুন।',
	'ACCOUNT_EMAIL_CHANGED'			=> 'আপনার অ্যাকাউন্ট আপডেট করা হয়েছে. যাইহোক, এই বোর্ড ইমেইল পরিবর্তন নেভিগেশন অ্যাকাউন্ট সক্রিয়করণ প্রয়োজন। একটি সক্রিয়করণ কী আপনার দেওয়া নতুন ইমেল ঠিকানাতে পাঠানো হয়েছে। আরো তথ্যের জন্য আপনার ইমেইল চেক করুন। ',
	'ACCOUNT_EMAIL_CHANGED_ADMIN'	=> 'আপনার অ্যাকাউন্ট আপডেট করা হয়েছে. যাইহোক, এই বোর্ড ইমেইল পরিবর্তনগুলিতে অ্যাডমিনিস্ট্রেটরদের দ্বারা অ্যাকাউন্ট পুনরায় সক্রিয়করণের প্রয়োজন। একটি ইমেইল তাদের কাছে পাঠানো হয়েছে এবং আপনার অ্যাকাউন্টটি পুনরায় সক্রিয় করা হলে আপনাকে জানানো হবে। ',
	'ACCOUNT_INACTIVE'				=> 'আপনার অ্যাকাউন্ট তৈরি করা হয়েছে. তবে, এই বোর্ড অ্যাকাউন্ট অ্যাক্টিভেশন প্রয়োজন। একটি অ্যাক্টিভেশন কী আপনার দেওয়া ইমেল ঠিকানায় পাঠানো হয়েছে। আরো তথ্যের জন্য আপনার ইমেইল চেক করুন এবং আপনার জাঙ্ক মেইল ​​বক্স চেক করতে ভুলবেন না। আপনার ইমেল সরবরাহকারীর উপর নির্ভর করে ইমেলটি পেতে কিছু সময় লাগবে। ',
	'ACCOUNT_INACTIVE_ADMIN'		=> 'আপনার অ্যাকাউন্ট তৈরি করা হয়েছে. যাইহোক, এই বোর্ড প্রশাসক গ্রুপ দ্বারা অ্যাকাউন্ট অ্যাক্টিভেশন প্রয়োজন। একটি ইমেইল তাদের কাছে পাঠানো হয়েছে এবং আপনার অ্যাকাউন্ট সক্রিয় করা হলে আপনাকে জানানো হবে। ',
	'ACTIVATION_EMAIL_SENT'			=> 'আপনার ইমেল ঠিকানাতে অ্যাক্টিভেশন ইমেল পাঠানো হয়েছে।',
	'ACTIVATION_EMAIL_SENT_ADMIN'	=> 'অ্যাক্টিভেশন ইমেইল অ্যাডমিনিস্ট্রেটরদের ইমেল ঠিকানাগুলিতে পাঠানো হয়েছে।',
	'ADD'							=> 'জুড়ুন',
	'ADD_BCC'						=> 'Add [BCC]',
	'ADD_FOES'						=> 'Add new foes',
	'ADD_FOES_EXPLAIN'				=> 'আপনি প্রতিটি লাইনের বিভিন্ন ব্যবহারকারীর নাম লিখতে পারেন।',
	'ADD_FOLDER'					=> 'ফোল্ডার যোগ করুন',
	'ADD_FRIENDS'					=> 'নতুন বন্ধু যোগ করুন',
	'ADD_FRIENDS_EXPLAIN'			=> 'আপনি প্রতিটি লাইনের বিভিন্ন ব্যবহারকারীর নাম লিখতে পারেন।',
	'ADD_NEW_RULE'					=> 'নতুন নিয়ম যোগ করুন',
	'ADD_RULE'						=> 'নিয়ম যোগ করুন',
	'ADD_TO'						=> 'যোগ করা[to]',
	'ADD_USERS_UCP_EXPLAIN'			=> 'এখানে আপনি গ্রুপে নতুন ব্যবহারকারীদের যোগ করতে পারেন। নির্বাচিত ব্যবহারকারীদের জন্য এই দলটি নতুন ডিফল্ট হয়ে গেলে আপনি নির্বাচন করতে পারেন। দয়া করে প্রতিটি ব্যবহারকারীর নাম একটি পৃথক রেখায় লিখুন। ',
	'ADMIN_EMAIL'					=> 'অ্যাডমিনিস্ট্রেটররা আমাকে ইমেইল করতে পারেন ',
	'AGREE'							=> 'এগিয়ে চলুন',
	'ALLOW_PM'						=> 'ব্যবহারকারীদের আপনাকে ব্যক্তিগত বার্তা পাঠাতে অনুমতি দিন',
	'ALLOW_PM_EXPLAIN'				=> 'উল্লেখ্য যে প্রশাসক এবং নিয়ন্ত্রকেরা সবসময় আপনাকে বার্তা পাঠাতে সক্ষম হবে।',
	'ALREADY_ACTIVATED'				=> 'আপনি ইতিমধ্যেই আপনার অ্যাকাউন্ট সক্রিয় করেছেন।',
	'ATTACHMENTS_EXPLAIN'			=> 'এই বোর্ডে পোস্ট করা সংযুক্তিগুলির তালিকা এটি।',
	'ATTACHMENTS_DELETED'			=> 'সংযুক্তি সফলভাবে মোছা হয়েছে।',
	'ATTACHMENT_DELETED'			=> 'সংযুক্তি সফলভাবে মোছা হয়েছে।',
	'AUTOLOGIN_SESSION_KEYS_DELETED'=> 'নির্বাচিত আমাকে মনে রাখুন লগইন কীগুলি সফলভাবে মোছা হয়েছে।',
	'AVATAR_CATEGORY'				=> 'বিভাগ',
	'AVATAR_DRIVER_GRAVATAR_TITLE'	=> 'Gravatar',
	'AVATAR_DRIVER_GRAVATAR_EXPLAIN'=> 'Gravatar is a service that allows you to maintain the same avatar across multiple websites. Visit <a href="http://www.gravatar.com/">Gravatar</a> for more information.',
	'AVATAR_DRIVER_LOCAL_TITLE'		=> 'গ্যালারি অবতার',
	'AVATAR_DRIVER_LOCAL_EXPLAIN'	=> 'আপনি স্থানীয়ভাবে উপলব্ধ অবতারগুলির থেকে আপনার অবতার চয়ন করতে পারেন।',
	'AVATAR_DRIVER_REMOTE_TITLE'	=> 'দূরবর্তী অবতার',
	'AVATAR_DRIVER_REMOTE_EXPLAIN'	=> 'অন্য ওয়েবসাইট থেকে অবতার ইমেজ লিঙ্ক।',
	'AVATAR_DRIVER_UPLOAD_TITLE'	=> 'অবতার আপলোড করুন',
	'AVATAR_DRIVER_UPLOAD_EXPLAIN'	=> 'আপনার নিজস্ব কাস্টম অবতার আপলোড করুন। ',
	'AVATAR_EXPLAIN'				=> 'সর্বোচ্চ মাত্রা:  প্রস্থ: %1$s, উচ্চতা: %2$s, ফাইলের আকার: %3$.2f KiB.',
	'AVATAR_EXPLAIN_NO_FILESIZE'	=> 'সর্বোচ্চ মাত্রা:  প্রস্থ: %1$s, উচ্চতা: %2$s.',
	'AVATAR_FEATURES_DISABLED'		=> 'অবতার কার্যকারিতা বর্তমানে নিষ্ক্রিয় রয়েছে।',
	'AVATAR_GALLERY'				=> 'স্থানীয় গ্যালারি',
	'AVATAR_GENERAL_UPLOAD_ERROR'	=> '%s এ অবতার আপলোড করা যায়নি।',
	'AVATAR_NOT_ALLOWED'			=> 'আপনার অবতার প্রদর্শন করা যাবে না কারণ অবতারগণকে অমান্য করা হয়েছে।',
	'AVATAR_PAGE'					=> 'পৃষ্ঠা',
	'AVATAR_SELECT'					=> 'আপনার অবতার নির্বাচন করুন',
	'AVATAR_TYPE'					=> 'অবতার টাইপ',
	'AVATAR_TYPE_NOT_ALLOWED'		=> 'আপনার বর্তমান অবতারটি প্রদর্শন করা যাবে না কারণ এর প্রকারটি অনুমোদিত নয়।',

	'BACK_TO_DRAFTS'			=> 'সংরক্ষিত খসড়াগুলিতে ফিরুন',
	'BACK_TO_LOGIN'				=> 'লগইন স্ক্রিনে ফিরে',
	'BIRTHDAY'					=> 'জন্মদিনের',
	'BIRTHDAY_EXPLAIN'			=> 'আপনার জন্মদিনের সময় আপনার বয়স নির্ধারণ করা হবে।',
	'BOARD_DATE_FORMAT'			=> 'আমার তারিখ বিন্যাস',
	'BOARD_DATE_FORMAT_EXPLAIN'	=> 'ব্যবহার করা সিনট্যাক্স পিএইচপি (পিএইচপি) এর মতই হয়। <a href="http://www.php.net/date"> date() </a> ফাংশন।',
	'BOARD_LANGUAGE'			=> 'আমার ভাষা',
	'BOARD_STYLE'				=> 'আমার বোর্ড স্টাইল',
	'BOARD_TIMEZONE'			=> 'টাইমজোন',
	'BOOKMARKS'					=> 'বুকমার্কগুলি',
	'BOOKMARKS_EXPLAIN'			=> 'আপনি ভবিষ্যতের  জন্য টপিকগুলি বুকমার্ক করতে পারেন। আপনি মুছে ফেলতে চান এমন কোনও বুকমার্কের জন্য চেকবক্সটি নির্বাচন করুন, তারপর চিহ্নিত বুকমার্কস বোতাম <em>সরান</em> টিপুন।',
	'BOOKMARKS_DISABLED'		=> 'এই বোর্ডে বুকমার্ক অক্ষম।',
	'BOOKMARKS_REMOVED'			=> 'বুকমার্ক সফলভাবে মুছে ফেলা হয়েছে।',

	'CANNOT_EDIT_MESSAGE_TIME'	=> 'আপনি যে বার্তাটি আর সম্পাদনা বা মুছে ফেলতে পারবেন না।',
	'CANNOT_MOVE_TO_SAME_FOLDER'=> 'যে ফোল্ডার আপনি সরাতে চান তা বার্তাগুলি সরানো যাবে না।',
	'CANNOT_MOVE_FROM_SPECIAL'	=> 'বার্তাগুলি আউটবক্স থেকে সরানো যাবে না।',
	'CANNOT_RENAME_FOLDER'		=> 'এই ফোল্ডারটির পুনঃনামকরণ করা যাবে না।',
	'CANNOT_REMOVE_FOLDER'		=> 'এই ফোল্ডারটি সরানো যাবে না।',
	'CHANGE_DEFAULT_GROUP'		=> 'ডিফল্ট গ্রুপ পরিবর্তন করুন',
	'CHANGE_PASSWORD'			=> 'পাসওয়ার্ড পরিবর্তন',
	'CLICK_GOTO_FOLDER'			=> '%1$sGo to your “%3$s” folder%2$s',
	'CLICK_RETURN_FOLDER'		=> '%1$sReturn to your “%3$s” folder%2$s',
	'CONFIRMATION'				=> 'নিবন্ধন নিশ্চিতকরণ',
	'CONFIRM_CHANGES'			=> 'পরিবর্তন নিশ্চিত',
	'CONFIRM_EXPLAIN'			=> 'To prevent automated registrations the board requires you to enter a confirmation code. The code is displayed in the image you should see below. If you are visually impaired or cannot otherwise read this code please contact the %sBoard Administrator%s.',
	'VC_REFRESH'				=> 'Refresh confirmation code',
	'VC_REFRESH_EXPLAIN'		=> 'If you cannot read the code you can request a new one by clicking the button.',

	'CONFIRM_PASSWORD'			=> 'পাসওয়ার্ড নিশ্চিত করুন',
	'CONFIRM_PASSWORD_EXPLAIN'	=> 'আপনি যদি এটি উপরে পরিবর্তন করে থাকেন তবে শুধুমাত্র আপনার পাসওয়ার্ড নিশ্চিত করতে হবে। ',
	'COPPA_BIRTHDAY'			=> 'রেজিস্ট্রেশন প্রক্রিয়া চালিয়ে যাওয়ার জন্য আমাদের বলুন যখন আপনি জন্মগ্রহণ করেন।',
	'COPPA_COMPLIANCE'			=> 'সিপ্পা সম্মতি',
	'COPPA_EXPLAIN'				=> 'Please note that clicking submit will create your account. However it cannot be activated until a parent or guardian approves your registration. You will be emailed a copy of the necessary form with details of where to send it.',
	'CREATE_FOLDER'				=> 'ফোল্ডার যোগ করুন…',
	'CURRENT_IMAGE'				=> 'বর্তমান চিত্র',
	'CURRENT_PASSWORD'			=> 'বর্তমান পাসওয়ার্ড',
	'CURRENT_PASSWORD_EXPLAIN'	=> 'আপনি যদি আপনার ইমেইল ঠিকানা বা ইউজারনেম পরিবর্তন করতে চান তবে আপনাকে অবশ্যই আপনার বর্তমান পাসওয়ার্ডটি লিখতে হবে। ',
	'CURRENT_CHANGE_PASSWORD_EXPLAIN' => 'আপনার পাসওয়ার্ড পরিবর্তন করতে, আপনার ইমেইল ঠিকানা বা আপনার ইউজারনেম, আপনাকে অবশ্যই আপনার বর্তমান পাসওয়ার্ড লিখতে হবে।',
	'CUR_PASSWORD_EMPTY'		=> 'আপনি আপনার বর্তমান পাসওয়ার্ড লিখেননি।',
	'CUR_PASSWORD_ERROR'		=> 'আপনার প্রবেশ করা বর্তমান পাসওয়ার্ডটি ভুল।',
	'CUSTOM_DATEFORMAT'			=> 'কাস্টম ...',

	'DEFAULT_ACTION'			=> 'ডিফল্ট অ্যাকশন',
	'DEFAULT_ACTION_EXPLAIN'	=> 'উপরের কোনটি প্রযোজ্য না হলে এই পদক্ষেপটি চালু হবে।',
	'DEFAULT_ADD_SIG'			=> 'ডিফল্টরূপে আমার স্বাক্ষর সংযুক্ত',
	'DEFAULT_BBCODE'			=> 'ডিফল্টরূপে BBCode সক্রিয় করুন',
	'DEFAULT_NOTIFY'			=> 'ডিফল্টভাবে উত্তরগুলিতে আমাকে অবহিত করুন',
	'DEFAULT_SMILIES'			=> 'ডিফল্টভাবে স্মাইলি সক্ষম করুন',
	'DEFINED_RULES'				=> 'নির্ধারিত নিয়ম',
	'DELETED_TOPIC'				=> 'বিষয় সরানো হয়েছে।',
	'DELETE_ATTACHMENT'			=> 'সংযুক্তি মুছুন',
	'DELETE_ATTACHMENTS'		=> 'সংযুক্তি মুছুন',
	'DELETE_ATTACHMENT_CONFIRM'	=> 'আপনি কি এই সংযুক্তিটি মুছতে চান?',
	'DELETE_ATTACHMENTS_CONFIRM'=> 'আপনি কি এই সংযুক্তিগুলি মুছে ফেলার ব্যাপারে নিশ্চিত?',
	'DELETE_AVATAR'				=> 'ইমেজ মুছুন',
	'DELETE_COOKIES_CONFIRM'	=> 'আপনি এই বোর্ড দ্বারা সেট করা সমস্ত কুকি মুছে ফেলতে চান?',
	'DELETE_MARKED_PM'			=> 'চিহ্নিত বার্তাগুলি মুছে দিন',
	'DELETE_MARKED_PM_CONFIRM'	=> 'আপনি কি সমস্ত চিহ্নিত বার্তাগুলি মুছে ফেলতে চান?',
	'DELETE_OLDEST_MESSAGES'	=> 'পুরোনো বার্তা মুছে ফেলুন',
	'DELETE_MESSAGE'			=> 'বার্তা মুছুন',
	'DELETE_MESSAGE_CONFIRM'	=> 'আপনি কি এই ব্যক্তিগত বার্তাটি মুছে ফেলতে চান?',
	'DELETE_MESSAGES_IN_FOLDER'	=> 'সরানো ফোল্ডারের মধ্যে সমস্ত বার্তা মুছে ফেলুন',
	'DELETE_RULE'				=> 'নীতি মুছে ফেলুন',
	'DELETE_RULE_CONFIRM'		=> 'তুমি কি এই নিয়মটি মুছে ফেলতে চাও?',
	'DEMOTE_SELECTED'			=> 'নির্বাচন বিলম্বিত',
	'DISABLE_CENSORS'			=> 'শব্দ সেন্সর সক্ষম করুন',
	'DISPLAY_GALLERY'			=> 'প্রদর্শন গ্যালারি',
	'DOMAIN_NO_MX_RECORD_EMAIL'	=> 'প্রবেশ করা ইমেল ডোমেনে কোন বৈধ MX রেকর্ড নেই।',
	'DOWNLOADS'					=> 'ডাউনলোডগুলি',
	'DRAFTS_DELETED'			=> 'সমস্ত নির্বাচিত খসড়া সফলভাবে মোছা হয়েছে।',
	'DRAFTS_EXPLAIN'			=> 'এখানে আপনি আপনার সংরক্ষিত খসড়া দেখতে, সম্পাদনা এবং মুছে ফেলতে পারেন।',
	'DRAFT_UPDATED'				=> 'খসড়া সফলভাবে আপডেট করা হয়েছে।',

	'EDIT_DRAFT_EXPLAIN'		=> 'এখানে আপনি আপনার খসড়া সম্পাদনা করতে পারবেন। খসড়া সংযুক্তি এবং পোল তথ্য থাকে না। ',
	'EMAIL_BANNED_EMAIL'		=> 'আপনার প্রবেশ করা ইমেল ঠিকানাটি ব্যবহার করা অনুমোদিত নয়।',
	'EMAIL_REMIND'				=> 'এটি আপনার অ্যাকাউন্টের সাথে যুক্ত ইমেল ঠিকানা হতে হবে। আপনি যদি আপনার ব্যবহারকারী নিয়ন্ত্রণ প্যানেলের মাধ্যমে এটি পরিবর্তন না করে থাকেন তবে এটি ইমেল ঠিকানা যা আপনি আপনার অ্যাকাউন্টে নিবন্ধিত করেছেন।',
	'EMAIL_TAKEN_EMAIL'			=> 'প্রদানকৃত ইমেইল ঠিকানাটি ইতোমধ্যে ব্যবহার করা হয়েছে।',
	'EMPTY_DRAFT'				=> 'আপনার পরিবর্তনগুলি জমা দিতে আপনাকে একটি বার্তা প্রবেশ করতে হবে।',
	'EMPTY_DRAFT_TITLE'			=> 'You must enter a draft title.',
	'EXPORT_AS_XML'				=> 'Export as XML',
	'EXPORT_AS_CSV'				=> 'Export as CSV',
	'EXPORT_AS_CSV_EXCEL'		=> 'Export as CSV (Excel)',
	'EXPORT_AS_TXT'				=> 'Export as TXT',
	'EXPORT_AS_MSG'				=> 'Export as MSG',
	'EXPORT_FOLDER'				=> 'Export this view',

	'FIELD_REQUIRED'					=> 'The field “%s” must be completed.',
	'FIELD_TOO_SHORT'					=> array(
		1	=> 'The field “%2$s” is too short, a minimum of %1$d character is required.',
		2	=> 'The field “%2$s” is too short, a minimum of %1$d characters is required.',
	),
	'FIELD_TOO_LONG'					=> array(
		1	=> 'The field “%2$s” is too long, a maximum of %1$d character is allowed.',
		2	=> 'The field “%2$s” is too long, a maximum of %1$d characters is allowed.',
	),
	'FIELD_TOO_SMALL'					=> 'The value of “%2$s” is too small, a minimum value of %1$d is required.',
	'FIELD_TOO_LARGE'					=> 'The value of “%2$s” is too large, a maximum value of %1$d is allowed.',
	'FIELD_INVALID_CHARS_INVALID'		=> 'The field “%s” has invalid characters.',
	'FIELD_INVALID_CHARS_NUMBERS_ONLY'	=> 'The field “%s” has invalid characters, only numbers are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_DOTS'	=> 'The field “%s” has invalid characters, only alphanumeric or . characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_ONLY'	=> 'The field “%s” has invalid characters, only alphanumeric characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_PUNCTUATION'	=> 'The field “%s” has invalid characters, only alphanumeric or _,-. characters are allowed and the first character must be alphabetic.',
	'FIELD_INVALID_CHARS_ALPHA_SPACERS'	=> 'The field “%s” has invalid characters, only alphanumeric, space or -+_[] characters are allowed.',
	'FIELD_INVALID_CHARS_ALPHA_UNDERSCORE'	=> 'The field “%s” has invalid characters, only alphanumeric or _ characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_DOTS'	=> 'The field “%s” has invalid characters, only letter, number or . characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_ONLY'	=> 'The field “%s” has invalid characters, only letter and number characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_PUNCTUATION'	=> 'The field “%s” has invalid characters, only letter, number or _,-. characters are allowed and the first character must be alphabetic.',
	'FIELD_INVALID_CHARS_LETTER_NUM_SPACERS'		=> 'The field “%s” has invalid characters, only letter, number, space or -+_[] characters are allowed.',
	'FIELD_INVALID_CHARS_LETTER_NUM_UNDERSCORE'		=> 'The field “%s” has invalid characters, only letter, number or _ characters are allowed.',
	'FIELD_INVALID_DATE'				=> 'The field “%s” has an invalid date.',
	'FIELD_INVALID_URL'					=> 'The field “%s” has an invalid url.',
	'FIELD_INVALID_VALUE'				=> 'The field “%s” has an invalid value.',

	'FOE_MESSAGE'				=> 'Message from foe',
	'FOES_EXPLAIN'				=> 'Foes are users which will be ignored by default. Posts by these users will not be fully visible. Personal messages from foes are still permitted. Please note that you cannot ignore moderators or administrators.',
	'FOES_UPDATED'				=> 'Your foes list has been updated successfully.',
	'FOLDER_ADDED'				=> 'Folder successfully added.',
	'FOLDER_MESSAGE_STATUS'		=> array(
		1	=> '%2$d out of %1$s stored',
		2	=> '%2$d out of %1$s stored',
	),
	'FOLDER_NAME_EMPTY'			=> 'You must enter a name for this folder.',
	'FOLDER_NAME_EXIST'			=> 'Folder <strong>%s</strong> already exists.',
	'FOLDER_OPTIONS'			=> 'Folder options',
	'FOLDER_RENAMED'			=> 'Folder successfully renamed.',
	'FOLDER_REMOVED'			=> 'Folder successfully removed.',
	'FOLDER_STATUS_MSG'			=> array(
		1	=> 'Folder is %3$d%% full (%2$d out of %1$s stored)',
		2	=> 'Folder is %3$d%% full (%2$d out of %1$s stored)',
	),
	'FORWARD_PM'				=> 'ফরওয়ার্ড PM',
	'FORCE_PASSWORD_EXPLAIN'	=> 'বোর্ড ব্রাউজিং চালিয়ে যাওয়ার আগে আপনাকে আপনার পাসওয়ার্ড পরিবর্তন করতে হবে।',
	'FRIEND_MESSAGE'			=> 'বন্ধু থেকে বার্তা',
	'FRIENDS'					=> 'বন্ধুরা',
	'FRIENDS_EXPLAIN'			=> 'বন্ধুগণ আপনার সাথে প্রায়শই যোগাযোগ করে এমন সদস্যদের কাছে দ্রুত অ্যাক্সেস সক্ষম করে। যদি টেমপ্লেটটি কোন বন্ধু দ্বারা তৈরি কোনও পোস্টের সাথে প্রাসঙ্গিক সমর্থন করে তবে হাইলাইট হতে পারে। ',
	'FRIENDS_OFFLINE'			=> 'অফলাইন',
	'FRIENDS_ONLINE'			=> 'অনলাইন',
	'FRIENDS_UPDATED'			=> 'আপনার বন্ধুদের তালিকা সফলভাবে আপডেট করা হয়েছে।',
	'FULL_FOLDER_OPTION_CHANGED'=> 'যখন একটি ফোল্ডার পূর্ণ হয় তখন যে পদক্ষেপ নেয়া হবে তা সফলভাবে পরিবর্তিত হয়েছে।',
	'FWD_ORIGINAL_MESSAGE'		=> '-------- আসল বার্তা --------',
	'FWD_SUBJECT'				=> 'বিষয় :% s',
	'FWD_DATE'					=> 'তারিখ:% s',
	'FWD_FROM'					=> 'Form :% s',
	'FWD_TO'					=> 'To :% s',

	'GLOBAL_ANNOUNCEMENT'		=> 'Global announcement',

	'GRAVATAR_AVATAR_EMAIL'			=> 'Gravatar email',
	'GRAVATAR_AVATAR_EMAIL_EXPLAIN'	=> 'Enter the email address you used for registering your account on <a href="http://www.gravatar.com/">Gravatar</a>.',
	'GRAVATAR_AVATAR_SIZE'			=> 'Avatar dimensions',
	'GRAVATAR_AVATAR_SIZE_EXPLAIN'	=> 'Specify the width and height of the avatar, leave blank to attempt automatic verification.',

	'HIDE_ONLINE'				=> 'আমার অনলাইন অবস্থা লুকান',
	'HIDE_ONLINE_EXPLAIN'		=> 'বোর্ডে আপনার পরবর্তী সফর পর্যন্ত এই সেটিং পরিবর্তন করা কার্যকর হবে না।',
	'HOLD_NEW_MESSAGES'			=> 'নতুন বার্তাগুলি গ্রহণ করবেন না (পর্যাপ্ত স্থান উপলব্ধ না হওয়া পর্যন্ত নতুন বার্তাগুলি রাখা হবে)',
	'HOLD_NEW_MESSAGES_SHORT'	=> 'নতুন বার্তাগুলি আটকে রাখা হবে',

	'IF_FOLDER_FULL'			=> 'ফোল্ডারটি পূর্ণ হলে',
	'IMPORTANT_NEWS'			=> 'গুরুত্বপূর্ণ ঘোষণা',
	'INVALID_USER_BIRTHDAY'		=> 'প্রবেশ করা জন্মদিনটি বৈধ তারিখ নয়।',
	'INVALID_CHARS_USERNAME'	=> 'ব্যবহারকারীর নাম নিষিদ্ধ অক্ষর রয়েছে।',
	'INVALID_CHARS_NEW_PASSWORD'=> 'পাসওয়ার্ডটিতে প্রয়োজনীয় অক্ষর নেই।',
	'ITEMS_REQUIRED'			=> 'চিহ্নিত আইটেমগুলি প্রোফাইল ক্ষেত্রের প্রয়োজন এবং ভর্তি করা প্রয়োজন।',

	'JOIN_SELECTED'				=> 'নির্বাচিত যোগ',

	'LANGUAGE'					    => 'ভাষা',
	'LINK_REMOTE_AVATAR'		    => 'লিংক অফ-সাইট',
	'LINK_REMOTE_AVATAR_EXPLAIN'    => 'আপনি লিঙ্ক করতে চান এমন অবতার চিত্র ধারণকারী অবস্থানের URL টি লিখুন।',
	'LINK_REMOTE_SIZE'			    => 'অবতার মাত্রা',
	'LINK_REMOTE_SIZE_EXPLAIN'	    => 'অবতারের প্রস্থ ও উচ্চতা নির্দিষ্ট করুন, স্বয়ংক্রিয় যাচাইয়ের চেষ্টা করতে ফাঁকা রাখুন।',
	'LOGIN_EXPLAIN_UCP'			    => 'ব্যবহারকারী কন্ট্রোল প্যানেল অ্যাক্সেস করতে দয়া করে লগইন করুন।',
	'LOGIN_LINK'					=> 'আপনার বোর্ড অ্যাকাউন্টের সাথে একটি বহিরাগত পরিষেবাতে লিঙ্ক বা নিবন্ধন করুন',
	'LOGIN_LINK_EXPLAIN'			=> 'আপনি একটি বহিরাগত পরিষেবাতে লগইন করার চেষ্টা করেছেন যা এখনও এই বোর্ডের একটি অ্যাকাউন্টের সাথে সংযুক্ত নয়। আপনি এখন এই অ্যাকাউন্টটি একটি বিদ্যমান অ্যাকাউন্টে লিঙ্ক করতে বা একটি নতুন অ্যাকাউন্ট তৈরি করতে হবে। ',
	'LOGIN_LINK_MISSING_DATA'		=> 'আপনার অ্যাকাউন্টকে একটি বহিরাগত পরিষেবা দিয়ে লিঙ্ক করতে প্রয়োজনীয় ডেটা উপলব্ধ নয়। দয়া করে লগইন প্রক্রিয়া পুনরায় শুরু করুন। ',
	'LOGIN_LINK_NO_DATA_PROVIDED'	=> 'কোনও একটি ফোরাম অ্যাকাউন্টে একটি বহিরাগত অ্যাকাউন্ট লিঙ্ক করতে এই পৃষ্ঠায় কোন তথ্য সরবরাহ করা হয়নি। যদি আপনি সমস্যার সম্মুখীন হন তবে বোর্ড প্রশাসকের সাথে যোগাযোগ করুন। ',
	'LOGIN_KEY'					    => 'লগইন কী',
	'LOGIN_TIME'				    => 'লগ ইন টাইম',
	'LOGIN_REDIRECT'			    => 'আপনি সফলভাবে লগ ইন করেছেন।',
	'LOGOUT_FAILED'				    => 'আপনার লগ আউট করা হয়নি, কারণ অনুরোধটি আপনার সেশনের সাথে মেলে না। যদি আপনি সমস্যার সম্মুখীন হন তবে বোর্ড প্রশাসকের সাথে যোগাযোগ করুন। ',
	'LOGOUT_REDIRECT'			    => 'আপনি সফলভাবে লগ আউট হয়েছে।',

	'MARK_IMPORTANT'				=> 'গুরুত্বপূর্ণ হিসাবে চিহ্ন / অচিহ্নিত হিসাবে চিহ্নিত',
	'MARKED_MESSAGE'				=> 'চিহ্নিত বার্তা',
	'MAX_FOLDER_REACHED'			=> 'অনুমোদিত ব্যবহারকারীর সংজ্ঞায়িত ফোল্ডারগুলির সর্বাধিক সংখ্যা পৌঁছে গেছেন।',
	'MESSAGE_BY_AUTHOR'				=> 'দ্বারা',
	'MESSAGE_COLOURS'				=> 'বার্তা রং',
	'MESSAGE_DELETED'				=> 'বার্তা সফলভাবে মুছে ফেলা হয়েছে।',
	'MESSAGE_EDITED'				=> 'বার্তা সফলভাবে সম্পাদিত।',
	'MESSAGE_HISTORY'				=> 'বার্তা ইতিহাস',
	'MESSAGE_REMOVED_FROM_OUTBOX'	=> 'এই বার্তা তার লেখক দ্বারা মুছে ফেলা হয়েছে।',
	'MESSAGE_SENT_ON'				=> 'উপর',
	'MESSAGE_STORED'				=> 'এই বার্তাটি সফলভাবে পাঠানো হয়েছে।',
	'MESSAGE_TO'					=> 'To',
	'MESSAGES_DELETED'				=> 'বার্তা সফলভাবে মুছে ফেলা',
	'MOVE_DELETED_MESSAGES_TO'		=> 'সরানো ফোল্ডার থেকে বার্তা সরান',
	'MOVE_DOWN'						=> 'নিচে যাও',
	'MOVE_MARKED_TO_FOLDER'			=> '% S- এ চিহ্নিত করুন',
	'MOVE_PM_ERROR'					=> array(
		1	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s was moved.',
		2	=> 'An error occurred while moving the messages to the new folder, only %2$d out of %1$s were moved.',
	),
	'MOVE_TO_FOLDER'				=> 'ফোল্ডারে সরানো',
	'MOVE_UP'						=> 'উপরে উঠানো',

	'NEW_FOLDER_NAME'				=> 'নতুন ফোল্ডার নাম',
	'NEW_PASSWORD'					=> 'নতুন পাসওয়ার্ড',
	'NEW_PASSWORD_CONFIRM_EMPTY'	=> 'খালি ছেড়ে যেতে পারেন না।',
	'NEW_PASSWORD_ERROR'			=> 'পাসওয়ার্ড মেলেনি।',

	'NOTIFICATIONS_MARK_ALL_READ'						=> 'সমস্ত বিজ্ঞপ্তি পড়া মার্ক',
	'NOTIFICATIONS_MARK_ALL_READ_CONFIRM'				=> 'আপনি কি সমস্ত বিজ্ঞপ্তিগুলি পড়তে চান তা নিশ্চিত?',
	'NOTIFICATIONS_MARK_ALL_READ_SUCCESS'				=> 'সমস্ত বিজ্ঞপ্তি পড়া হয়েছে চিহ্নিত করা হয়েছে।',
	'NOTIFICATION_GROUP_MISCELLANEOUS'					=> 'বিবিধ বিজ্ঞপ্তি',
	'NOTIFICATION_GROUP_MODERATION'						=> 'মডারেশন বিজ্ঞপ্তি',
	'NOTIFICATION_GROUP_ADMINISTRATION'					=> 'প্রশাসন বিজ্ঞপ্তি',
	'NOTIFICATION_GROUP_POSTING'						=> 'পোস্টিং বিজ্ঞপ্তি',
	'NOTIFICATION_METHOD_BOARD'							=> 'বিজ্ঞপ্তিগুলি',
	'NOTIFICATION_METHOD_EMAIL'							=> 'ইমেল',
	'NOTIFICATION_METHOD_JABBER'						=> 'জব্বারের',
	'NOTIFICATION_TYPE'									=> 'বিজ্ঞপ্তি টাইপ',
	'NOTIFICATION_TYPE_BOOKMARK'						=> 'কেউ আপনার একটি বুকমার্ক একটি বিষয় জবাব',
	'NOTIFICATION_TYPE_GROUP_REQUEST'					=> 'কেউ আপনার নেতৃত্বে একটি গ্রুপ যোগ দিতে অনুরোধ',
	'NOTIFICATION_TYPE_IN_MODERATION_QUEUE'				=> 'একটি পোস্ট বা বিষয়ের অনুমোদন প্রয়োজন',
	'NOTIFICATION_TYPE_MODERATION_QUEUE'				=> 'আপনার বিষয়গুলি / পোস্টগুলি একজন নিয়ন্ত্রকের দ্বারা অনুমোদিত বা অপ্রত্যাশিত',
	'NOTIFICATION_TYPE_PM'								=> 'কেউ আপনাকে একটি ব্যক্তিগত বার্তা পাঠায়',
	'NOTIFICATION_TYPE_POST'							=> 'যে কাউকে আপনি সদস্যতা নিয়েছেন এমন একটি বিষয়ে উত্তর দিয়েছেন',
	'NOTIFICATION_TYPE_QUOTE'							=> 'কেউ আপনাকে একটি পোস্ট উদ্ধৃত',
	'NOTIFICATION_TYPE_REPORT'							=> 'কেউ পোস্ট পোস্ট করেছেন',
	'NOTIFICATION_TYPE_TOPIC'							=> 'কেউ ফোরামে এমন কোন বিষয় তৈরি করেন যার উপরে আপনি সদস্যতা নেন',
	'NOTIFICATION_TYPE_ADMIN_ACTIVATE_USER'				=> 'ব্যবহারকারীর অ্যাক্টিভেশন প্রয়োজন',

	'NOTIFY_METHOD'					=> 'বিজ্ঞপ্তি পদ্ধতি',
	'NOTIFY_METHOD_BOTH'			=> 'উভয়',
	'NOTIFY_METHOD_EMAIL'			=> 'শুধুমাত্র ইমেল',
	'NOTIFY_METHOD_EXPLAIN'			=> 'এই বোর্ডের মাধ্যমে পাঠানো বার্তা পাঠানোর পদ্ধতি।',
	'NOTIFY_METHOD_IM'				=> 'জববার কেবল',
	'NOTIFY_ON_PM'					=> 'নতুন ব্যক্তিগত বার্তাগুলিতে আমাকে অবহিত করুন',
	'NOT_ADDED_FRIENDS_ANONYMOUS'	=> 'আপনি বেনামী ব্যবহারকারীকে আপনার বন্ধুদের তালিকায় যুক্ত করতে পারবেন না।',
	'NOT_ADDED_FRIENDS_BOTS'		=> 'আপনি আপনার বন্ধুদের তালিকায় বোট যোগ করতে পারবেন না।',
	'NOT_ADDED_FRIENDS_FOES'		=> 'আপনি আপনার শত্রুদের তালিকায় যারা আপনার বন্ধুদের তালিকায় ব্যবহারকারী যোগ করতে পারবেন না।',
	'NOT_ADDED_FRIENDS_SELF'		=> 'আপনি নিজের বন্ধুদের তালিকাতে যোগ করতে পারবেন না।',
	'NOT_ADDED_FOES_MOD_ADMIN'		=> 'আপনি প্রশাসক ও নিয়ন্ত্রককে আপনার শত্রুদের তালিকাতে যুক্ত করতে পারবেন না।',
	'NOT_ADDED_FOES_ANONYMOUS'		=> 'আপনি বেনামী ব্যবহারকারীকে আপনার শত্রুদের তালিকায় যুক্ত করতে পারবেন না।',
	'NOT_ADDED_FOES_BOTS'			=> 'আপনি আপনার শত্রুদের তালিকায় বট যোগ করতে পারবেন না।',
	'NOT_ADDED_FOES_FRIENDS'		=> 'আপনার বন্ধুরা আপনার তালিকার তালিকায় আপনার ব্যবহারকারীদের তালিকা যোগ করতে পারবেন না।',
	'NOT_ADDED_FOES_SELF'			=> 'আপনি শত্রু তালিকায় নিজেকে যোগ করতে পারবেন না।',
	'NOT_AGREE'						=> 'আমি একমত নই',
	'NOT_ENOUGH_SPACE_FOLDER'		=> 'The destination folder “%s” seems to be full. The requested action has not been taken.',
	'NOT_MOVED_MESSAGES'			=> array(
		1	=> 'You have %d private message currently on hold because of full folder.',
		2	=> 'You have %d private messages currently on hold because of full folder.',
	),
	'NO_ACTION_MODE'				=> 'কোনও বার্তা ক্রিয়া নির্দিষ্ট নয়।',
	'NO_AUTHOR'						=> 'কোনও লেখক এই বার্তাটির জন্য সংজ্ঞায়িত করেনি',
	'NO_AVATAR'						=> 'কোন অবতার নির্বাচিত নেই',
	'NO_AVATAR_CATEGORY'			=> 'কিছুই নয়',

	'NO_AUTH_DELETE_MESSAGE'		=> 'আপনি ব্যক্তিগত বার্তাগুলি মুছে ফেলতে অনুমোদিত নন।',
	'NO_AUTH_EDIT_MESSAGE'			=> 'আপনি ব্যক্তিগত বার্তাগুলি সম্পাদনা করতে অনুমোদিত নন।',
	'NO_AUTH_FORWARD_MESSAGE'		=> 'আপনি ব্যক্তিগত বার্তা ফরওয়ার্ড করার জন্য অনুমোদিত নয়।',
	'NO_AUTH_GROUP_MESSAGE'			=> 'আপনি গোষ্ঠীগুলিতে ব্যক্তিগত বার্তা পাঠাতে অনুমোদিত নন।',
	'NO_AUTH_PASSWORD_REMINDER'		=> 'আপনি একটি নতুন পাসওয়ার্ড অনুরোধ করতে অনুমোদিত নয়।',
	'NO_AUTH_PROFILEINFO'			=> 'আপনি আপনার প্রোফাইল তথ্য পরিবর্তন করার জন্য অনুমোদিত নয়।',
	'NO_AUTH_READ_HOLD_MESSAGE'		=> 'আপনি ধরে রাখা ব্যক্তিগত বার্তাগুলি পড়ার জন্য অনুমোদিত নয়।',
	'NO_AUTH_READ_MESSAGE'			=> 'আপনি ব্যক্তিগত বার্তা পড়ার জন্য অনুমোদিত নয়।',
	'NO_AUTH_READ_REMOVED_MESSAGE'	=> 'আপনি এই বার্তাটি পড়তে পারবেন না কারণ এটি লেখক কর্তৃক সরানো হয়েছে।',
	'NO_AUTH_SEND_MESSAGE'			=> 'আপনি ব্যক্তিগত বার্তা পাঠাতে অনুমোদিত নন।',
	'NO_AUTH_SIGNATURE'				=> 'আপনি একটি স্বাক্ষর নির্ধারণ করতে অনুমোদিত হয় না।',

	'NO_BCC_RECIPIENT'			=> 'কিছুই নয়',
	'NO_BOOKMARKS'				=> 'আপনার কোন বুকমার্ক আছে।',
	'NO_BOOKMARKS_SELECTED'		=> 'আপনি কোন বুকমার্ক নির্বাচন করেছেন।',
	'NO_EDIT_READ_MESSAGE'		=> 'ব্যক্তিগত বার্তাটি সম্পাদনা করা যাবে না কারণ এটি ইতিমধ্যেই পড়েছে।',
	'NO_EMAIL_USER'				=> 'ইমেইল / ব্যবহারকারীর নাম জমা দেওয়া তথ্য পাওয়া যায়নি।',
	'NO_FOES'					=> 'কোন foes বর্তমানে সংজ্ঞায়িত',
	'NO_FRIENDS'				=> 'কোন বন্ধু বর্তমানে সংজ্ঞায়িত',
	'NO_FRIENDS_OFFLINE'		=> 'কোন বন্ধু অফলাইন',
	'NO_FRIENDS_ONLINE'			=> 'কোন বন্ধুরা অনলাইন',
	'NO_GROUP_SELECTED'			=> 'কোন গ্রুপ নির্দিষ্ট।',
	'NO_IMPORTANT_NEWS'			=> 'কোন গুরুত্বপূর্ণ ঘোষণা উপস্থিত নেই।',
	'NO_MESSAGE'				=> 'ব্যক্তিগত বার্তা পাওয়া যায়নি।',
	'NO_NEW_FOLDER_NAME'		=> 'আপনাকে একটি নতুন ফোল্ডার নাম উল্লেখ করতে হবে।',
	'NO_NEWER_PM'				=> 'কোন নতুন বার্তা নেই।',
	'NO_OLDER_PM'				=> 'পুরানো কোন বার্তা নেই।',
	'NO_PASSWORD_SUPPLIED'		=> 'আপনি পাসওয়ার্ড ছাড়তে পারেন না৷',
	'NO_RECIPIENT'				=> 'কোন প্রাপক নির্ধারিত।',
	'NO_RULES_DEFINED'			=> 'কোন নিয়ম সংজ্ঞায়িত।',
	'NO_SAVED_DRAFTS'			=> 'কোন খসড়া সংরক্ষিত।',
	'NO_TO_RECIPIENT'			=> 'কিছুই নয়',
	'NO_WATCHED_FORUMS'			=> 'আপনি কোন ফোরামে সাবস্ক্রাইব করা হয় না।',
	'NO_WATCHED_SELECTED'		=> 'আপনি কোন সাবস্ক্রাইব করা বিষয় বা ফোরাম নির্বাচন করেননি।',
	'NO_WATCHED_TOPICS'			=> 'আপনি কোনও বিষয়ের সদস্যতা নেন।',

	'PASS_TYPE_ALPHA_EXPLAIN'	=> 'Password must be between %1$s and %2$s long, must contain letters in mixed case and must contain numbers.',
	'PASS_TYPE_ANY_EXPLAIN'		=> 'অবশ্যই %1$s থেকে %2$s অক্ষরের মধ্যে হতে হবে।',
	'PASS_TYPE_CASE_EXPLAIN'	=> 'Password must be between %1$s and %2$s long and must contain letters in mixed case.',
	'PASS_TYPE_SYMBOL_EXPLAIN'	=> 'Password must be between %1$s and %2$s long, must contain letters in mixed case, must contain numbers and must contain symbols.',
	'PASSWORD'					=> 'পাসওয়ার্ড',
	'PASSWORD_ACTIVATED'		=> 'নতুন পাসওয়ার্ড সক্রিয় করা হয়েছে।',
	'PASSWORD_UPDATED'			=> 'ইমেইল ঠিকানায়  নতুন পাসওয়ার্ড পাঠানো হয়েছে।',
	'PERMISSIONS_RESTORED'		=> 'মূল অনুমতি পুনর্বহাল করা হয়েছে।',
	'PERMISSIONS_TRANSFERRED'	=> 'Successfully transferred permissions from <strong>%s</strong>, you are now able to browse the board with this user’s permissions.<br />Please note that admin permissions were not transferred. You are able to revert to your permission set at any time.',
	'PM_DISABLED'				=> 'এই বোর্ডে ব্যক্তিগত বার্তা অক্ষম করা হয়েছে।',
	'PM_FROM'					=> 'থেকে',
	'PM_FROM_REMOVED_AUTHOR'	=> 'এই বার্তাটি এখন আর নিবন্ধিত ব্যবহারকারীর দ্বারা পাঠানো হয়নি।',
	'PM_ICON'					=> 'প্রধানমন্ত্রী আইকন',
	'PM_INBOX'					=> 'ইনবক্স',
	'PM_MARK_ALL_READ'			=> 'সব বার্তা পড়া চিহ্নিত করুন',
	'PM_MARK_ALL_READ_SUCCESS'	=> 'এই ফোল্ডারে সমস্ত ব্যক্তিগত বার্তা পড়া হয়েছে চিহ্নিত করা হয়েছে',
	'PM_NO_USERS'				=> 'যোগ করা ব্যবহারকারীদের অস্তিত্ব নেই।',
	'PM_OUTBOX'					=> 'আউটবক্স',
	'PM_SENTBOX'				=> 'প্রেরিত বার্তা',
	'PM_SUBJECT'				=> 'বার্তা বিষয়',
	'PM_TO'						=> 'পাঠানো',
	'PM_TOOLS'					=> 'বার্তা সরঞ্জাম',
	'PM_USERS_REMOVED_NO_PERMISSION'	=> 'কিছু ব্যবহারকারী যুক্ত করা যাবে না কারণ তাদের ব্যক্তিগত বার্তাগুলি পড়ার অনুমতি নেই।',
	'PM_USERS_REMOVED_NO_PM'	=> 'ব্যক্তিগত বার্তা প্রাপ্তির অক্ষম থাকার কারণে কিছু ব্যবহারকারী যুক্ত করা যাবে না।',
	'POST_EDIT_PM'				=> 'বার্তা সম্পাদন করুন',
	'POST_FORWARD_PM'			=> 'ফরওয়ার্ড মেসেজ',
	'POST_NEW_PM'				=> 'বার্তা রচনা',
	'POST_PM_LOCKED'			=> 'ব্যক্তিগত বার্তা লক আছে।',
	'POST_PM_POST'				=> 'উদ্ধৃতি পোস্ট',
	'POST_QUOTE_PM'				=> 'উদ্ধৃতি বার্তা',
	'POST_REPLY_PM'				=> 'বার্তা জবাব',
	'PRINT_PM'					=> 'প্রিন্ট ভিউ',
	'PREFERENCES_UPDATED'		=> 'আপনার পছন্দগুলি আপডেট করা হয়েছে। ',
	'PROFILE_INFO_NOTICE'		=> 'দয়া করে মনে রাখবেন যে এই তথ্য অন্যান্য সদস্যদের কাছে দর্শনীয় হতে পারে। কোনো ব্যক্তিগত বিবরণ সহ যখন সতর্ক থাকুন কোন * ক্ষেত্রের সাথে চিহ্নিত * সম্পন্ন করা আবশ্যক। ',
	'PROFILE_UPDATED'			=> 'আপনার প্রোফাইল আপডেট করা হয়েছে.',
	'PROFILE_AUTOLOGIN_KEYS'	=> 'যখন আপনি বোর্ডে যান তখন "আমাকে মনে রাখুন" লগইন কীগুলি আপনাকে লগ ইন করে। যদি আপনি লগ আউট করেন তবে মনে রাখবেন যে লগইন করার জন্য আপনি ব্যবহার করছেন এমন কম্পিউটারে শুধুমাত্র লগইন কীটি মুছে ফেলা হয়। এখানে আপনি এই কম্পিউটারে অ্যাক্সেসের জন্য ব্যবহৃত অন্যান্য কম্পিউটারে তৈরি লগইন কীগুলি মনে রাখতে পারেন। ',
	'PROFILE_NO_AUTOLOGIN_KEYS'	=> 'কোন "লগইন কি" সংরক্ষিত নেই।',

	'RECIPIENT'							=> 'প্রাপক',
	'RECIPIENTS'						=> 'প্রাপক',
	'REGISTRATION'						=> 'নিবন্ধন',
	'RELEASE_MESSAGES'					=> '%sRelease all on-hold messages%s… they will be re-sorted into the appropriate folder if enough space is made available.',
	'REMOVE_ADDRESS'					=> 'ঠিকানা সরান',
	'REMOVE_SELECTED_BOOKMARKS'			=> 'নির্বাচিত বুকমার্কগুলি সরান',
	'REMOVE_SELECTED_BOOKMARKS_CONFIRM'	=> 'আপনি কি সমস্ত নির্বাচিত বুকমার্কগুলি মুছে ফেলতে চান?',
	'REMOVE_BOOKMARK_MARKED'			=> 'চিহ্নিত বুকমার্কগুলি সরান',
	'REMOVE_FOLDER'						=> 'ফোল্ডার সরান',
	'REMOVE_FOLDER_CONFIRM'				=> 'আপনি কি এই ফোল্ডারটি সরাতে চান?',
	'RENAME'							=> 'পুনঃনামকরণ',
	'RENAME_FOLDER'						=> 'পুনঃনামকরণ ফোল্ডার',
	'REPLIED_MESSAGE'					=> 'বার্তা জবাব দিয়েছে',
	'REPLY_TO_ALL'						=> 'প্রেরক এবং সকল প্রাপককে উত্তর দিন।',
	'REPORT_PM'							=> 'ব্যক্তিগত বার্তা প্রতিবেদন করুন',
	'RESIGN_SELECTED'					=> 'মনোনীত নির্বাচিত',
	'RETURN_FOLDER'						=> '% 1 $ s পূর্ববর্তী ফোল্ডার% 2 $ s তে ফেরান',
	'RETURN_UCP'						=> '% S ব্যবহারকারীর কন্ট্রোল প্যানেল %s তে ফিরে যান',
	'RULE_ADDED'						=> 'রুল সফলভাবে যোগ হয়েছে।',
	'RULE_ALREADY_DEFINED'				=> 'এই নিয়ম আগে সংজ্ঞায়িত ছিল।',
	'RULE_DELETED'						=> 'রুল সফলভাবে সরানো হয়েছে।',
	'RULE_LIMIT_REACHED'				=> 'আপনি আরও প্রধানমন্ত্রী নীতিমালা যোগ করতে পারবেন না আপনি সর্বোচ্চ সংখ্যক নিয়মগুলিতে পৌঁছেছেন। ',
	'RULE_NOT_DEFINED'					=> 'রায় সঠিকভাবে নির্দিষ্ট করা হয়নি।',
	'RULE_REMOVED_MESSAGES'				=> array(
		1	=> '%d private message was removed due to private message filters.',
		2	=> '%d private messages were removed due to private message filters.',
	),

	'SAME_PASSWORD_ERROR'		=> 'আপনার প্রবেশ করা নতুন পাসওয়ার্ড আপনার বর্তমান পাসওয়ার্ডের মতই।',
	'SEARCH_YOUR_POSTS'			=> 'আপনার পোস্ট দেখান',
	'SEND_PASSWORD'				=> 'পাসওয়ার্ড পাঠান',
	'SENT_AT'					=> 'প্রেরিত', // ব্যক্তিগত বার্তাগুলিতে তারিখগুলি আগে ব্যবহৃত
	'SHOW_EMAIL'				=> 'ব্যবহারকারীরা ইমেলের মাধ্যমে আমার সাথে যোগাযোগ করতে পারেন',
	'SIGNATURE_EXPLAIN'			=> 'এটি পাঠ্যের একটি ব্লক যা আপনি পোস্টগুলিতে যোগ করতে পারেন। একটি% d অক্ষর সীমা আছে। ',
	'SIGNATURE_PREVIEW'			=> 'আপনার স্বাক্ষর এই পোস্টে প্রদর্শিত হবে',
	'SIGNATURE_TOO_LONG'		=> 'আপনার স্বাক্ষরটি অনেক দীর্ঘ।',
	'SELECT_CURRENT_TIME'		=> 'বর্তমান সময় নির্বাচন করুন',
	'SELECT_TIMEZONE'			=> 'টাইমজোন নির্বাচন করুন',
	'SORT'						=> 'সাজান',
	'SORT_COMMENT'				=> 'ফাইলের মন্তব্য',
	'SORT_DOWNLOADS'			=> 'ডাউনলোডগুলি',
	'SORT_EXTENSION'			=> 'এক্সটেনশন',
	'SORT_FILENAME'				=> 'ফাইলের নাম',
	'SORT_POST_TIME'			=> 'পোস্ট সময়',
	'SORT_SIZE'					=> 'ফাইলের আকার',

	'TIMEZONE'					=> 'সময় অঞ্চল',
	'TIMEZONE_DATE_SUGGESTION'	=> 'পরামর্শ:% s',
	'TIMEZONE_INVALID'			=> 'আপনার নির্বাচিত টাইমজোনটি অবৈধ।',
	'TO'						=> 'প্রাপক',
	'TO_MASS'					=> 'প্রাপক',
	'TO_ADD'					=> 'প্রাপক যোগ',
	'TO_ADD_MASS'				=> 'প্রাপক যোগ করুন',
	'TO_ADD_GROUPS'				=> 'গ্রুপ জুড়ুন',
	'TOO_MANY_RECIPIENTS'		=> 'আপনি অনেক প্রাপকদের একটি ব্যক্তিগত বার্তা পাঠানোর চেষ্টা করেছেন।',
	'TOO_MANY_REGISTERS'		=> 'আপনি এই সেশন জন্য নিবন্ধন প্রচেষ্টা সর্বাধিক সংখ্যা অতিক্রম করেছেন। অনুগ্রহ করে একটু পরে আবার চেষ্টা করুন.',

	'UCP'						=> 'ব্যবহারকারী কন্ট্রোল প্যানেল',
	'UCP_ACTIVATE'				=> 'অ্যাকাউন্ট সক্রিয়',
	'UCP_ADMIN_ACTIVATE'		=> 'দয়া করে মনে রাখবেন আপনার অ্যাকাউন্ট সক্রিয় হওয়ার আগে আপনাকে একটি বৈধ ইমেল ঠিকানা লিখতে হবে। অ্যাডমিনিস্ট্রেটর আপনার একাউন্টের পর্যালোচনা করবে এবং অনুমোদিত হলে আপনি যে ঠিকানাটি নির্দিষ্ট করেছেন তার একটি ইমেইল পাবেন। ',
	'UCP_ATTACHMENTS'			=> 'সংযুক্তিসমূহ',
	'UCP_AUTH_LINK'				=> 'বাহ্যিক অ্যাকাউন্ট',
	'UCP_AUTH_LINK_ASK'			=> 'আপনি বর্তমানে এই বহিরাগত পরিষেবা সঙ্গে যুক্ত কোনো অ্যাকাউন্ট নেই। আপনার বহিরাগত সেবা সঙ্গে একটি অ্যাকাউন্টে আপনার বোর্ড অ্যাকাউন্ট লিঙ্ক করতে নীচের বাটন ক্লিক করুন। ',
	'UCP_AUTH_LINK_ID'			=> 'অনন্য শনাক্তকারী',
	'UCP_AUTH_LINK_LINK'		=> 'লিঙ্কটি',
	'UCP_AUTH_LINK_MANAGE'		=> 'বাহ্যিক অ্যাকাউন্ট অ্যাসোসিয়েশন পরিচালনা',
	'UCP_AUTH_LINK_NOT_SUPPORTED'=>'বহিরাগত পরিষেবাগুলিতে বোর্ড অ্যাকাউন্ট লিঙ্ক এই বোর্ডের বর্তমান প্রমাণীকরণ পদ্ধতি দ্বারা সমর্থিত নয়।',
	'UCP_AUTH_LINK_TITLE'		=> 'আপনার সোশ্যাল অ্যাকাউন্ট গুলো পরিচালনা করুন।',
	'UCP_AUTH_LINK_UNLINK'		=> 'লিঙ্কমুক্ত',
	'UCP_COPPA_BEFORE'			=> '%s এর আগে',
	'UCP_COPPA_ON_AFTER'		=> '%s বা পরে',
	'UCP_EMAIL_ACTIVATE'		=> 'দয়া করে মনে রাখবেন আপনার অ্যাকাউন্ট সক্রিয় হওয়ার আগে আপনাকে একটি বৈধ ইমেল ঠিকানা লিখতে হবে। আপনি একটি ঠিকানা অ্যাক্টিভেশন লিঙ্ক রয়েছে এমন ঠিকানাটি ইমেল পাবেন। ',
	'UCP_JABBER'				=> 'জববার ঠিকানা',
	'UCP_LOGIN_LINK'			=> 'একটি বহিঃস্থ অ্যাকাউন্ট অ্যাসোসিয়েশন সেট আপ',

	'UCP_MAIN'					=> 'সংক্ষিপ্ত বিবরণ',
	'UCP_MAIN_ATTACHMENTS'		=> 'সংযুক্তি পরিচালনা করুন',
	'UCP_MAIN_BOOKMARKS'		=> 'বুকমার্কগুলি পরিচালনা করুন',
	'UCP_MAIN_DRAFTS'			=> 'ড্রাফ্ট পরিচালনা করুন',
	'UCP_MAIN_FRONT'			=> 'প্রথম পাতা',
	'UCP_MAIN_SUBSCRIBED'		=> 'সাবস্ক্রিপশন পরিচালনা',

	'UCP_NO_ATTACHMENTS'		=> 'আপনি কোন ফাইল পোস্ট করেন না',

	'UCP_NOTIFICATION_LIST'				=> 'বিজ্ঞপ্তিগুলি পরিচালনা করুন',
	'UCP_NOTIFICATION_LIST_EXPLAIN'		=> 'এখানে আপনি সমস্ত অতীতের বিজ্ঞপ্তিগুলি দেখতে পারেন।',
	'UCP_NOTIFICATION_OPTIONS'			=> 'নোটিশ অপশন সম্পাদনা করুন',
	'UCP_NOTIFICATION_OPTIONS_EXPLAIN'	=> 'এখানে আপনি বোর্ডের জন্য আপনার পছন্দসই বিজ্ঞপ্তি পদ্ধতি সেট করতে পারেন।',

	'UCP_PREFS'					=> 'বোর্ড সেটিংস',
	'UCP_PREFS_PERSONAL'		=> 'গ্লোবাল সেটিংস সম্পাদনা ',
	'UCP_PREFS_POST'			=> 'পোস্টিং ডিফল্ট সম্পাদনা ',
	'UCP_PREFS_VIEW'			=> 'ডিসপ্লে অপশন সম্পাদনা ',

	'UCP_PM'					=> 'ব্যক্তিগত বার্তাসমূহ',
	'UCP_PM_COMPOSE'			=> 'বার্তা রচনা',
	'UCP_PM_DRAFTS'				=> 'pm খসড়া পরিচালনা',
	'UCP_PM_OPTIONS'			=> 'Rules, folders &amp; settings',
	'UCP_PM_UNREAD'				=> 'অপঠিত বার্তা',
	'UCP_PM_VIEW'				=> 'বার্তা দেখুন',

	'UCP_PROFILE'				=> 'প্রোফাইল',
	'UCP_PROFILE_AVATAR'		=> 'অবতার সম্পাদনা ',
	'UCP_PROFILE_PROFILE_INFO'	=> 'জীবন বৃত্তান্ত সম্পাদনা',
	'UCP_PROFILE_REG_DETAILS'	=> 'অ্যাকাউন্ট সেটিংস সম্পাদনা ',
	'UCP_PROFILE_SIGNATURE'		=> 'স্বাক্ষর সম্পাদনা করুন',
	'UCP_PROFILE_AUTOLOGIN_KEYS'=> 'পরিচালনা করুন, আমাকে মনে রাখবেন "লগইন কি" ',

	'UCP_USERGROUPS'			=> 'ইউজারগ্রুপ',
	'UCP_USERGROUPS_MEMBER'		=> 'সদস্যতা সম্পাদনা করুন',
	'UCP_USERGROUPS_MANAGE'		=> 'গ্রুপ পরিচালনা করুন',

	'UCP_PASSWORD_RESET_DISABLED'	=> 'পাসওয়ার্ড পুনরায় সেট করার কার্যকারিতা অক্ষম করা হয়েছে। আপনার অ্যাকাউন্ট অ্যাক্সেস করতে সাহায্য প্রয়োজন হলে, দয়া করে  %sBoard Administrator%s এর সাথে যোগাযোগ করুন',
	'UCP_REGISTER_DISABLE'			=> 'নতুন অ্যাকাউন্ট তৈরি করা বর্তমানে সম্ভব নয়।',
	'UCP_REMIND'					=> 'পাসওয়ার্ড পাঠান',
	'UCP_RESEND'					=> 'সক্রিয়করণ ইমেল পাঠান',
	'UCP_WELCOME'					=> 'কন্ট্রোল প্যানেল এ স্বাগতম। এখান থেকে আপনি আপনার প্রোফাইল, পছন্দগুলি, সাবস্ক্রাইবকৃত ফোরাম এবং টপিকগুলি নিরীক্ষণ, দেখুন এবং আপডেট করতে পারেন। আপনি অন্যান্য ব্যবহারকারীদের বার্তা পাঠাতে পারেন (অনুমোদিত হলে)। অবিরত করার আগে আপনি কোন ঘোষণা পড়তে দয়া করে নিশ্চিত করুন।u can also send messages to other users (if permitted). Please ensure you read any announcements before continuing.',
	'UCP_ZEBRA'						=> 'বন্ধু &amp; শত্রুরা ',
	'UCP_ZEBRA_FOES'				=> 'শত্রুদের পরিচালনা করুন',
	'UCP_ZEBRA_FRIENDS'				=> 'বন্ধুদের পরিচালনা করুন',
	'UNDISCLOSED_RECIPIENT'			=> 'অপ্রকাশিত প্রাপক',
	'UNKNOWN_FOLDER'				=> 'অজানা ফোল্ডার',
	'UNWATCH_MARKED'				=> 'অজানা ফোল্ডার',
	'UPLOAD_AVATAR_FILE'			=> 'অবিচ্ছিন্ন চিহ্নিত',
	'UPLOAD_AVATAR_URL'				=> 'আপনার মেশিন থেকে আপলোড করুন',
	'UPLOAD_AVATAR_URL_EXPLAIN'		=> 'Enter the URL of the location containing the image. The image will be copied to this site.',
	'USERNAME_ALPHA_ONLY_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only alphanumeric characters.',
	'USERNAME_ALPHA_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use alphanumeric, space or -+_[] characters.',
	'USERNAME_ASCII_EXPLAIN'		=> 'Username must be between %1$s and %2$s long and use only ASCII characters, so no special symbols.',
	'USERNAME_LETTER_NUM_EXPLAIN'	=> 'Username must be between %1$s and %2$s long and use only letter or number characters.',
	'USERNAME_LETTER_NUM_SPACERS_EXPLAIN'=> 'Username must be between %1$s and %2$s long and use letter, number, space or -+_[] characters.',
	'USERNAME_CHARS_ANY_EXPLAIN'	=> 'অবশ্যই %1$s থেকে %2$s অক্ষরের মধ্যে হতে হবে।',
	'USERNAME_TAKEN_USERNAME'		=> 'আপনার প্রবেশ করা ব্যবহারকারী নামটি ইতিমধ্যেই ব্যবহৃত হচ্ছে, দয়া করে বিকল্প নির্বাচন করুন।',
	'USERNAME_DISALLOWED_USERNAME'	=> 'আপনার প্রবেশ করা ব্যবহারকারী নামটি অবহিত হয়েছে বা একটি অজ্ঞাত শব্দ রয়েছে। দয়া করে একটি ভিন্ন নাম চয়ন করুন। ',
	'USER_NOT_FOUND_OR_INACTIVE'	=> 'আপনি যে ব্যবহারকারী নামগুলি নির্দিষ্ট করেছেন তা পাওয়া যাবে না বা ব্যবহারকারীদের সক্রিয় করা যাবে না।',

	'VIEW_AVATARS'				=> 'প্রদর্শন avatars',
	'VIEW_EDIT'					=> 'দেখুন / সম্পাদনা করুন',
	'VIEW_FLASH'				=> 'ফ্ল্যাশ অ্যানিমেশন প্রদর্শন করুন',
	'VIEW_IMAGES'				=> 'পোস্টের মধ্যে ইমেজ প্রদর্শন',
	'VIEW_NEXT_HISTORY'			=> 'ইতিহাসের পরবর্তী PM',
	'VIEW_NEXT_PM'				=> 'পরবর্তী PM',
	'VIEW_PM'					=> 'বার্তা দেখুন',
	'VIEW_PM_INFO'				=> 'বার্তা বিশদ',
	'VIEW_PM_MESSAGES'			=> array(
		1	=> '%d message',
		2	=> '%d messages',
	),
	'VIEW_PREVIOUS_HISTORY'		=> 'ইতিহাসের পূর্ববর্তী PM',
	'VIEW_PREVIOUS_PM'			=> 'পূর্ববর্তী PM',
	'VIEW_PROFILE'				=> 'প্রোফাইল',
	'VIEW_SIGS'					=> 'প্রদর্শন স্বাক্ষর',
	'VIEW_SMILIES'				=> 'স্মাইলিকে প্রদর্শন করে ছবি',
	'VIEW_TOPICS_DAYS'			=> 'আগের দিন থেকে টপিক প্রদর্শন',
	'VIEW_TOPICS_DIR'			=> 'টপিক নির্দেশ নির্দেশ প্রদর্শন করুন',
	'VIEW_TOPICS_KEY'			=> 'সাজানো বিষয় প্রদর্শন করে',
	'VIEW_POSTS_DAYS'			=> 'আগের দিন থেকে পোস্ট প্রদর্শন',
	'VIEW_POSTS_DIR'			=> 'পোস্ট অর্ডারের নির্দেশ প্রদর্শন করুন',
	'VIEW_POSTS_KEY'			=> 'পোস্ট দ্বারা পোস্ট প্রদর্শন প্রদর্শন',

	'WATCHED_EXPLAIN'			=> 'নীচে ফোরামগুলির  তালিকা এবং আপনার সদস্যতা নেওয়া টপিকগুলির তালিকা। আপনি নতুন পোস্ট মধ্যে অবহিত করা হবে। ফোরাম বা বিষয়টিকে চিহ্নিত করতে সদস্যতা ত্যাগ করুন এবং তারপর <strong>আনওয়াচ মার্ক</strong> করা বোতাম টিপুন।',
	'WATCHED_FORUMS'			=> 'ফোরাম দেখুন',
	'WATCHED_TOPICS'			=> 'টপিক দেখুন',
	'WRONG_ACTIVATION'			=> 'যে অ্যাক্টিভেশন কী সরবরাহ করেছেন তা ডাটাবেসের সাথে মেলে না।',

	'YOUR_DETAILS'				=> 'কার্যকলাপ',
	'YOUR_FOES'					=> 'শত্রু',
	'YOUR_FOES_EXPLAIN'			=> 'ব্যবহারকারীর নাম মুছে ফেলার জন্য তাদের নির্বাচন করুন এবং জমা দিন।',
	'YOUR_FRIENDS'				=> 'আপনার বন্ধু',
	'YOUR_FRIENDS_EXPLAIN'		=> 'ব্যবহারকারীর নাম মুছে ফেলার জন্য তাদের নির্বাচন করুন এবং জমা দিন।',
	'YOUR_WARNINGS'				=> 'আপনার সতর্কতা স্তর',

	'PM_ACTION' => array(
		'PLACE_INTO_FOLDER'	=> 'ফোল্ডারে রাখুন',
		'MARK_AS_READ'		=> 'পঠিত হিসেবে চিহ্নিত করুন',
		'MARK_AS_IMPORTANT'	=> 'বার্তা নির্বাচিত করুন',
		'DELETE_MESSAGE'	=> 'বার্তা মুছুন',
	),
	'PM_CHECK' => array(
		'SUBJECT'	=> 'বিষয়',
		'SENDER'	=> 'প্রেরকের',
		'MESSAGE'	=> 'বার্তা',
		'STATUS'	=> 'বার্তা স্থিতি',
		'TO'		=> 'প্রেরিত',
	),
	'PM_RULE' => array(
		'IS_LIKE'		=> 'মত',
		'IS_NOT_LIKE'	=> 'মত না হয়',
		'IS'			=> 'হল',
		'IS_NOT'		=> 'এটি না',
		'BEGINS_WITH'	=> 'এর সাথে শুরু',
		'ENDS_WITH'		=> 'দিয়ে শেষ হয়',
		'IS_FRIEND'		=> 'বন্ধু',
		'IS_FOE'		=> 'শত্রু',
		'IS_USER'		=> 'ব্যবহারকারী',
		'IS_GROUP'		=> 'ইউজারগ্রুপে আছে',
		'ANSWERED'		=> 'এর উত্তরে',
		'FORWARDED'		=> 'ফরওয়ার্ড',
		'TO_GROUP'		=> 'আমার ডিফল্ট ইউজারগ্রুপে',
		'TO_ME'			=> 'আমাকে',
	),

	'GROUPS_EXPLAIN'	=> 'ইউজারগ্রুপগুলি প্রশাসকদের  প্রশাসনের জন্য বোর্ড প্রশাসক সক্ষম করে। ডিফল্ট ভাবে আপনি একটি নির্দিষ্ট গ্রুপে ডিফল্ট গ্রুপ থাকেন । এই গ্রুপটি কিভাবে আপনি অন্যান্য ব্যবহারকারীদের কাছে প্রদর্শিত হতে পারে। উদাহরণস্বরূপ আপনার ব্যবহারকারীর নাম রঙিন, কবি, র্যাংক ইত্যাদির উপর নির্ভর করে। অ্যাডমিনিস্ট্রেটররা এটির অনুমতির উপর নির্ভর করে আপনাকে আপনার ডিফল্ট গ্রুপ পরিবর্তন করার অনুমতি দিতে পারে। আপনি অন্যান্য গ্রুপে যোগদান বা অনুমোদিত হতে পারেন। কিছু গ্রুপ আপনাকে সামগ্রী দেখতে বা অন্যান্য ক্ষেত্রে আপনার ক্ষমতা বৃদ্ধি করার জন্য অনুমতি প্রয়োজন হয়।',
	'GROUP_LEADER'		=> 'নেতৃত্বের',
	'GROUP_MEMBER'		=> 'সদস্যতা',
	'GROUP_PENDING'		=> 'মুলতুবি সদস্যতা',
	'GROUP_NONMEMBER'	=> 'অ সদস্যতা',
	'GROUP_DETAILS'		=> 'গ্রুপ বিবরণ',

	'NO_LEADER'		=> 'কোন গ্রুপ নেতৃত্ব',
	'NO_MEMBER'		=> 'কোন গ্রুপ সদস্যতা',
	'NO_PENDING'	=> 'কোন স্থায়ী সদস্যপদ নেই',
	'NO_NONMEMBER'	=> 'কোনও সদস্য নয় সদস্য'
));
